name: Databerry on Fly.io
on:
  push:
    branches:
      - main
      - feature/slack-bot
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly/fly.toml
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}